In [7]:
import numpy as np
from sklearn.datasets import load_iris
from sklearn.cluster import KMeans
from sklearn.metrics import confusion_matrix, adjusted_rand_score

# 1. 데이터 로드 (4개 특성: 꽃받침 길이/너비, 꽃잎 길이/너비)
iris = load_iris()
X = iris.data
y = iris.target

# 2. K-Means 모델 생성 및 학습 (품종이 3개이므로 clusters=3)
km = KMeans(n_clusters=3, random_state=42)
km.fit(X)

# 3. 혼동 행렬(Confusion Matrix) 출력
print("=== Confusion Matrix ===")
print(confusion_matrix(y, km.labels_))
print()

# 4. Adjusted Rand Score(ARS) 계산 및 출력
ars = adjusted_rand_score(y, km.labels_)
print(f"Adjusted Rand Score (ARS): {ars:.4f}")

# 주석: setosa가 완벽 분리된 이유
# Setosa 품종은 나머지 두 품종(versicolor, virginica)과 비교했을 때 꽃잎과 꽃받침의 크기 특성이 공간상에서 완전히 독립적으로 멀리 떨어져 있기(공간적 고립) 때문이다.

=== Confusion Matrix ===
[[ 0 50  0]
 [ 3  0 47]
 [36  0 14]]

Adjusted Rand Score (ARS): 0.7163


In [4]:
iris.data

array([[5.1, 3.5, 1.4, 0.2],
       [4.9, 3. , 1.4, 0.2],
       [4.7, 3.2, 1.3, 0.2],
       [4.6, 3.1, 1.5, 0.2],
       [5. , 3.6, 1.4, 0.2],
       [5.4, 3.9, 1.7, 0.4],
       [4.6, 3.4, 1.4, 0.3],
       [5. , 3.4, 1.5, 0.2],
       [4.4, 2.9, 1.4, 0.2],
       [4.9, 3.1, 1.5, 0.1],
       [5.4, 3.7, 1.5, 0.2],
       [4.8, 3.4, 1.6, 0.2],
       [4.8, 3. , 1.4, 0.1],
       [4.3, 3. , 1.1, 0.1],
       [5.8, 4. , 1.2, 0.2],
       [5.7, 4.4, 1.5, 0.4],
       [5.4, 3.9, 1.3, 0.4],
       [5.1, 3.5, 1.4, 0.3],
       [5.7, 3.8, 1.7, 0.3],
       [5.1, 3.8, 1.5, 0.3],
       [5.4, 3.4, 1.7, 0.2],
       [5.1, 3.7, 1.5, 0.4],
       [4.6, 3.6, 1. , 0.2],
       [5.1, 3.3, 1.7, 0.5],
       [4.8, 3.4, 1.9, 0.2],
       [5. , 3. , 1.6, 0.2],
       [5. , 3.4, 1.6, 0.4],
       [5.2, 3.5, 1.5, 0.2],
       [5.2, 3.4, 1.4, 0.2],
       [4.7, 3.2, 1.6, 0.2],
       [4.8, 3.1, 1.6, 0.2],
       [5.4, 3.4, 1.5, 0.4],
       [5.2, 4.1, 1.5, 0.1],
       [5.5, 4.2, 1.4, 0.2],
       [4.9, 3

In [5]:
print(iris.target_names)

['setosa' 'versicolor' 'virginica']


In [ ]:
import numpy as np
import pandas as pd
from sklearn.datasets import load_wine
from sklearn.preprocessing import StandardScaler
from sklearn.cluster import KMeans

# 1. 데이터 로드 및 데이터프레임 변환
wine = load_wine()
X = wine.data
df = pd.DataFrame(X, columns=wine.feature_names)

# 2. StandardScaler로 스케일링 후 KMeans 학습
# [주석] K-Means는 데이터 간의 거리를 기반으로 군집화를 수행하므로, 각 특성(Feature)의 스케일(단위) 차이가 거리 계산에 왜곡을 주지 않도록 표준화(스케일링)가 필수적이다.
scaler = StandardScaler()
X_scaled = scaler.fit_transform(X)

# 최적의 군집 수(예: 3)로 K-Means 학습
km = KMeans(n_clusters=3, random_state=42)
km.fit(X_scaled)

# 3. 각 데이터가 속한 군집 중심과의 최소 거리 계산
# km.transform은 각 데이터로부터 모든 군집 중심까지의 거리를 반환하므로, min(axis=1)을 통해 가장 가까운 중심과의 거리를 구합니다.
distances = km.transform(X_scaled).min(axis=1)

# 4. np.percentile로 상위 5% 거리를 가진 데이터를 이상치 임계값으로 설정
threshold = np.percentile(distances, 95)
anomaly_idx = np.where(distances > threshold)[0]

# 5. 탐지된 이상치 특성 값을 df.iloc[anomaly_idx]로 출력
print(f"=== 탐지된 이상치 개수: {len(anomaly_idx)}개 (임계값: {threshold:.4f}) ===")
print(df.iloc[anomaly_idx])

=== 탐지된 이상치 개수: 9개 (임계값: 4.2889) ===
     alcohol  malic_acid   ash  alcalinity_of_ash  magnesium  total_phenols  \
59     12.37        0.94  1.36               10.6       88.0           1.98   
69     12.21        1.19  1.75               16.8      151.0           1.85   
73     12.99        1.67  2.60               30.0      139.0           3.30   
78     12.33        0.99  1.95               14.8      136.0           1.90   
95     12.47        1.52  2.20               19.0      162.0           2.50   
96     11.81        2.12  2.74               21.5      134.0           1.60   
110    11.46        3.74  1.82               19.5      107.0           3.18   
121    11.56        2.05  3.23               28.5      119.0           3.18   
158    14.34        1.68  2.70               25.0       98.0           2.80   

     flavanoids  nonflavanoid_phenols  proanthocyanins  color_intensity   hue  \
59         0.57                  0.28             0.42             1.95  1.05   
69        

1. 스케일링: 모든 특성의 범위를 공평하게
2. K값 지정: km = KMeans(n_clusters=3, random_state=42) 데이터를 몇 개의 그룹으로 나뉠 건지
3. 컴퓨터가 내부적으로 K-Means 방식을 사용해, 서로 최대한 멀리 떨어진 데이터 K개를 무작위로 골라 중심으로 임명.
4. 데이터들은 중심으로 소속, 모인 데이터들로 평균값을 내어 평균을 중심으로
5. 더 이상 결과에 변화가 없을 때까지 수렴